apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: null
  generation: 1
  labels:
    app: gearpump
  name: gearpump
  selfLink: /apis/extensions/v1beta1/namespaces/cloudfest-1/deployments/gearpump
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gearpump
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gearpump
    spec:
      containers:
      - env:
        - name: VCAP_APPLICATION
          valueFrom:
            configMapKeyRef:
              key: vcap.application
              name: oisp-config
        - name: VCAP_SERVICES
          valueFrom:
            configMapKeyRef:
              key: vcap.services
              name: oisp-config
        image: sbriscoeintel/oisp-gearpump-rule-engine:full
        imagePullPolicy: Always
        name: gearpump
        ports:
        - containerPort: 8090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
