apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: websocket-server
  name: websocket-server
  selfLink: /apis/extensions/v1beta1/namespaces/cloudfest-1/deployments/websocket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: websocket-server
    spec:
      containers:
      - args:
        - ./wait-for-it.sh
        - postgres:5432
        - -t
        - "300"
        - --
        - ./scripts/docker-start.sh
        env:
        - name: NODE_ENV
          value: local
        - name: VCAP_APPLICATION
          valueFrom:
            configMapKeyRef:
              key: vcap.application
              name: oisp-config
        - name: VCAP_SERVICES
          valueFrom:
            configMapKeyRef:
              key: vcap.services
              name: oisp-config
        image: sbriscoeintel/oisp-websocket-server
        imagePullPolicy: Always
        name: websocket-server
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/keys
          name: jwt-keys
          readOnly: true
        workingDir: /app
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      hostname: websocket-server
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jwt-keys
        secret:
          defaultMode: 420
          items:
          - key: jwt.publickey
            path: public.pem
          - key: jwt.privatekey
            path: private.pem
          secretName: oisp-secrets
status: {}
