apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gearpump
  name: gearpump
  selfLink: /api/v1/namespaces/cloudfest/services/gearpump
spec:
  ports:
  - name: "8090"
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: gearpump
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
