apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hbase
  name: hbase
  selfLink: /api/v1/namespaces/cloudfest-1/services/hbase
spec:
  clusterIP: None
  ports:
  - name: "2181"
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: "8085"
    port: 8085
    protocol: TCP
    targetPort: 8085
  - name: "9090"
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: "9095"
    port: 9095
    protocol: TCP
    targetPort: 9095
  - name: "16010"
    port: 16010
    protocol: TCP
    targetPort: 16010
  - name: "60000"
    port: 60000
    protocol: TCP
    targetPort: 60000
  - name: "60020"
    port: 60020
    protocol: TCP
    targetPort: 60020
  selector:
    app: hbase
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
