apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: kafka
  selfLink: /api/v1/namespaces/cloudfest/services/kafka
spec:
  ports:
  - name: kafka
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: zookeeper
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
