apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: redis
  selfLink: /api/v1/namespaces/cloudfest-1/services/redis
spec:
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
