apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: websocket-server
  name: websocket-server
  selfLink: /api/v1/namespaces/cloudfest-1/services/websocket-server
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: websocket-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
