apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  labels:
    app: hbase
  name: hbase-data-hbase-0
  selfLink: /api/v1/namespaces/cloudfest/persistentvolumeclaims/hbase-data-hbase-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: storage03
status: {}
