apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: null
  name: redis-data
  selfLink: /api/v1/namespaces/cloudfest-1/persistentvolumeclaims/redis-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: storage02
status: {}
